version: '3.7'

services:

  sample:
    container_name: orderfront
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - my-net
networks:
  my-net:
    driver: bridge